spring.application.name=api-gateway


server.port=8888
#user services
spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8001
spring.cloud.gateway.mvc.routes[0].predicates=Path=/user/**


#payment-services
spring.cloud.gateway.mvc.routes[1].id=payment-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8002
spring.cloud.gateway.mvc.routes[1].predicates=Path=/payment/**

